### ISSUE TITLE
num_predictions metric not returning expected value

### ISSUE THREAD

**Issue by areiner222** [cheind/py-motmetrics#64] opened 2019-12-19 18:49 UTC
I noticed that the num_predictions metric is defined twice in metrics.py (https://github.com/cheind/py-motmetrics/blob/125304fb53495de8a43f2768bf90eb932c4a87bb/motmetrics/metrics.py#L247). One uses the result of pred_frequencies while the other counts the rows in the matched dataframe. Both output the same value, but I don't follow how they are accounting for the uniqueness of the predicted ids. Why shouldn't the unique predicted ids be pred_frequencies.count()? Am I misunderstanding?

**Comment by jvlmdr** [comment] 2020-02-01 15:19
Thanks for identifying this. The issue is now fixed in the `develop` branch.
https://github.com/cheind/py-motmetrics/commit/b957b788046d0eb05a7c31eea2f8917b18d623f2

**Closed by jvlmdr** 2020-02-01 15:19 UTC
