### ISSUE TITLE
False positives are over-reported

### ISSUE THREAD

**Issue by jjk2673** [cheind/py-motmetrics#36] opened 2019-03-29 10:36 UTC
The motmetrics module seems to be reporting false positive tracks in situations when none exist. I confirmed this by running eval_motchallenge with the 2DMOT2015 ground truth files copied and used as the test results. The metric results are below - most are perfect, as would be expected, but FP can get quite high, and this affects downstream metrics like IDF1 and MOTA.

```
                 IDF1    IDP    IDR   Rcll   Prcn  GT  MT PT ML   FP FN IDs  FM   MOTA   MOTP
KITTI-13        90.1%  82.0% 100.0% 100.0%  82.0%  42  42  0  0  167  0   0   0  78.1% -0.000
ADL-Rundle-8   100.0% 100.0% 100.0% 100.0% 100.0%  28  28  0  0    0  0   0   0 100.0%  0.000
Venice-2       100.0% 100.0% 100.0% 100.0% 100.0%  26  26  0  0    0  0   0   0 100.0%  0.000
TUD-Campus     100.0% 100.0% 100.0% 100.0% 100.0%   8   8  0  0    0  0   0   0 100.0%  0.000
KITTI-17        93.2%  87.3% 100.0% 100.0%  87.3%   9   9  0  0   99  0   0   0  85.5% -0.000
ETH-Bahnhof     82.8%  70.6% 100.0% 100.0%  70.6% 171 171  0  0 2255  0   0   0  58.4%  0.000
PETS09-S2L1     98.1%  96.3% 100.0% 100.0%  96.3%  19  19  0  0  174  0   0   0  96.1%  0.000
TUD-Stadtmitte 100.0% 100.0% 100.0% 100.0% 100.0%  10  10  0  0    0  0   0   0 100.0%  0.000
ADL-Rundle-6   100.0% 100.0% 100.0% 100.0% 100.0%  24  24  0  0    0  0   0   0 100.0%  0.000
ETH-Sunnyday    98.9%  97.7% 100.0% 100.0%  97.7%  30  30  0  0   43  0   0   0  97.7%  0.000
ETH-Pedcross2   96.2%  92.7% 100.0% 100.0%  92.7% 133 133  0  0  495  0   0   0  92.1%  0.000
OVERALL         96.1%  92.5% 100.0% 100.0%  92.5% 500 500  0  0 3233  0   0   0  91.9%  0.000
```

I will look into this a bit and open a PR if I find the cause.

**Comment by jjk2673** [comment] 2019-03-29 14:47
I have found the reason behind this issue, here:

https://github.com/cheind/py-motmetrics/blob/master/motmetrics/apps/eval_motchallenge.py#L87

The test result files are loaded without checking the confidence argument, while the MOTChallenge standard says that tracks reported with a confidence of zero should be discarded. This results in false positives because the zero-confidences are ignored when reading from the ground truth files, but used when reading from the test result files.

**Comment by cheind** [comment] 2019-03-29 16:33
@jjk2673 Thanks for the investigation. I have been in close contact with the original authors of the motmetrics for matlab and we've coordinated and verified implementations. This must have slipped through somehow.

I wonder however if that was on purpose on my side. Why report something if it has zero confidence. I understand that we have zero conf with ground-truth (usually to manually mark invalid annotations later), but it seems superflous for test files.

I reached out to Anton to comment on this. 
```
Hi Anton,

Johnatan recently reported that py-motmetrics reports too many FPs for certain 
motchallenge files. He tracked down the issue that py-motmetrics does ignore 
entries with min-confidence less than 1 when reading ground truth files, but does 
not so for test files. As both read-file code lines are closely grouped together in 
source, I don't think this is an oversight on my side but was done on purpose. 
Could you comment on this?

[1] https://github.com/cheind/py-motmetrics/issues/36
```

**Comment by jjk2673** [comment] 2019-03-29 16:45
@cheind 

Thanks for the response, I understand that reasoning. If I had known that this was the cause from the beginning, then I probably would not have opened this issue. But given that I had already opened it, and that this behavior technically goes against MOTChallenge standards, I thought it best to report all the details. If you reach the conclusion that this behavior was implemented intentionally, I have no problem with this issue getting closed.

And by the way, thanks for your work on this repository. It has been very useful for me.

**Comment by cheind** [comment] 2019-03-31 05:57
@jjk2673 I'm quite happy that you found out that there is a mismatch between py-motmetrics and the matlab implementation. py-motmetrics has started as a 1:1 clone written in python and its important that it stays that way, so people can rely when they submit to challenges. I will coordinate with Anthon and we see what's the best way to resolve this.

Thanks Christoph

**Comment by antonmil** [comment] 2019-03-31 20:49
@jjk2673 thanks for reporting the issue. I'm trying to understand myself what exactly is happening. 

It is true that gt entries with status (confidence) 0 should be ignored. And since we do not consider the confidence of the submitted results for evaluation, all rows are actually counted, thus resulting in FPs in this case. I wonder why it never came up before to be honest, but it still looks to me like expected behavior. I do not remember running this experiment with the MOTChallenge Devkit, did you try?

Anton

**Comment by ergysr** [comment] 2019-04-01 01:52
The algorithms that compute the IDF1/MOTA metrics, which exclude the input parsing step, give perfect scores when the input is identical to the ground truth (tested with the Matlab MOTChallenge devkit). I remember that py-motmetrics had identical behavior on the algorithmic side.
So the the issue can be narrowed down to data parsing.

**Comment by cheind** [comment] 2019-04-03 05:17
> ... and since we do not consider the confidence of the submitted results for evaluation, all rows are actually counted, thus resulting in FPs in this case```

So I conclude from that that py-motmetrics shows intended behaviour?

**Comment by antonmil** [comment] 2019-04-03 05:49
> So I conclude from that that py-motmetrics shows intended behaviour?

It looks to me like it does. Would be great though if someone could actually run this check on the MOTChallenge DevKit and verify.

**Comment by ergysr** [comment] 2019-04-03 06:11
py-motmetrics has the same behavior as the official devkit. In summary there are differences in how the GT and Result files are parsed leading to seemingly imperfect scores. Yet the evaluation code gives perfect scores when the GT and Result variables are identical.

```
TUD-Stadtmitte
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
100.0 100.0 100.0|100.0 100.0  0.00|   10  10    0    0|     0     0     0     0| 100.0 100.0 100.0 
TUD-Campus
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
100.0 100.0 100.0|100.0 100.0  0.00|    8   8    0    0|     0     0     0     0| 100.0 100.0 100.0 
PETS09-S2L1
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 98.1 96.3 100.0|100.0  96.3  0.22|   19  19    0    0|   174     0     0     2|  96.1 100.0  96.1 
ETH-Bahnhof
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 82.8 70.6 100.0|100.0  70.6  2.25|  171 171    0    0|  2255     0     0   117|  58.4 100.0  58.4 
ETH-Sunnyday
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 98.9 97.7 100.0|100.0  97.7  0.12|   30  30    0    0|    43     0     0     7|  97.7 100.0  97.7 
ETH-Pedcross2
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 96.2 92.7 100.0|100.0  92.7  0.59|  133 133    0    0|   495     0     0     3|  92.1 100.0  92.1 
ADL-Rundle-6
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
100.0 100.0 100.0|100.0 100.0  0.00|   24  24    0    0|     0     0     0     1| 100.0 100.0 100.0 
ADL-Rundle-8
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
100.0 100.0 100.0|100.0 100.0  0.00|   28  28    0    0|     0     0     0     0| 100.0 100.0 100.0 
KITTI-13
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 90.1 82.0 100.0|100.0  82.0  0.49|   42  42    0    0|   167     0     0     0|  78.1 100.0  78.1 
KITTI-17
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 93.2 87.3 100.0|100.0  87.3  0.68|    9   9    0    0|    99     0     0     0|  85.5 100.0  85.5 
Venice-2
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
100.0 100.0 100.0|100.0 100.0  0.00|   26  26    0    0|     0     0     0     0| 100.0 100.0 100.0 


 ********************* Your MOT15 Results *********************
 IDF1  IDP  IDR| Rcll  Prcn   FAR|   GT  MT   PT   ML|    FP    FN   IDs    FM|  MOTA  MOTP MOTAL 
 96.1 92.5 100.0|100.0  92.5  0.59|  500 500    0    0|  3233     0     0   130|  91.9 100.0  91.9 
```

**Comment by cheind** [comment] 2019-04-03 06:26
Thanks for testing @ergysr. So I guess we can close this. The open question remains if this behavour should be noted somewhere, so others don't run into the same issue (which appears quite likely to me).

**Comment by ergysr** [comment] 2019-04-03 06:42
It would make sense to note this (applies to MOT15-17), however it's not a bug. As a user of the devkit, if I'm designing a tracker and then evaluating the results on MOT15, being aware of how the ground truth is parsed has little to do with how I would want to improve the tracker.

**Comment by antonmil** [comment] 2019-04-03 06:48
@cheind Yes, I say we close this. Thanks @jjk2673 for finding and reporting and everyone for testing.

@ergysr When you say 'perfect scores with identical variables', you mean 'identical variables' after parsing, right? So identical .txt files do not necessarily mean perfect scores. I agree with @cheind that we could mention it somewhere, just as a note to avoid future confusion.

**Comment by ergysr** [comment] 2019-04-03 06:52
@antonmil. Correct, identical .txt files don't necessarily mean perfect scores. However identical result matrices fed to the core evaluation algorithms give perfect scores.

**Comment by cheind** [comment] 2019-04-03 07:20
@ergysr I'm not sure if I follow correctly. I assumed the main point @jjk2673 raises is that if you submit test files containing entries with zero confidence (maybe because your tracker computed it that way), you get many spurious FPs that affect other metrics.

**Comment by ergysr** [comment] 2019-04-03 07:30
@cheind @jjk2673 You are right, indeed MOTChallenge [mentions](https://motchallenge.net/instructions/):

> For the ground truth and results, it acts as a flag whether the entry is to be considered. A value of 0 means that this particular instance is ignored in the evaluation, while any other value can be used to mark it as active.

It should be corrected to:

> For the ground truth ~~and results,~~ it acts as a flag whether the entry is to be considered. A value of 0 means that this particular instance is ignored in the evaluation, while any other value can be used to mark it as active.

The devkit only ignores ground truth with zero confidence, though it considers results regardless of their confidence.

**Comment by antonmil** [comment] 2019-04-03 07:51
@ergysr You're right. Fixed.

**Comment by cheind** [comment] 2019-04-03 07:55
thanks everyone!

**Closed by cheind** 2019-04-03 07:55 UTC

**Comment by jjk2673** [comment] 2019-04-03 09:14
> 
> 
> @cheind @jjk2673 You are right, indeed MOTChallenge [mentions](https://motchallenge.net/instructions/):
> 
> > For the ground truth and results, it acts as a flag whether the entry is to be considered. A value of 0 means that this particular instance is ignored in the evaluation, while any other value can be used to mark it as active.
> 
> It should be corrected to:
> 
> > For the ground truth and results, it acts as a flag whether the entry is to be considered. A value of 0 means that this particular instance is ignored in the evaluation, while any other value can be used to mark it as active.
> 
> The devkit only ignores ground truth with zero confidence, though it considers results regardless of their confidence.

Exactly, this is where I got the idea that those lines in the results should be ignored. Thanks @antonmil for fixing it.
